### ISSUE TITLE
approot inside RAML definition

### ISSUE THREAD

**Issue by kejace** [junjihashimoto/yesod-raml#2]
Right now the URI has to be hardcoded like `baseUri: http://host/route`. It would be great if one can either just supply a local version by `baseUri: /route` or to somehow use the `approot` variable from Yesod: `baseUri: {%approot}/route` and then have `yesod-raml` insert the host from the Yesod configuration.

**Comment by junjihashimoto** [comment]
`yesod-raml` ignores `host` of `baseUri: http://host/route`.
We can use any host-name which does not include `{%`.
For example, `baseUri: http://approot/route`.

Currently, `yesod-raml` can not parse `baseUri: {%approot}/route`,
because `{%approot}/route` is not URI and `parseUri`-function fails.

If we want to use  `baseUri: {%approot}/route`, I have two plans.

1, Just substitute `{%approot}`  for static string like `http://hogehoge` before running `parseUri`-function.
2, Use template library like hamlet for route-definition `yesod-raml`.

What do you think?

If `yesod-raml` generates help-document like https://github.com/kevinrenskers/raml2html (right now `yesod-raml`  can not generate the document.), I think plan-2 is better.
